# Generated by Django 4.2.5 on 2023-09-05 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiDocumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=255)),
                ('api_intro', models.TextField(default='intro')),
            ],
        ),
        migrations.CreateModel(
            name='ApiEndpoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_name', models.CharField(max_length=255)),
                ('endpoint_url', models.CharField(max_length=255)),
                ('endpoint_desc', models.CharField(max_length=255)),
                ('api_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roniib_api.apidocumentation')),
            ],
        ),
    ]
