# Generated by Django 4.2.5 on 2023-09-06 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APICategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('category_short', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ApiDocumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=255)),
                ('short_name', models.CharField(default='s_name', max_length=255)),
                ('api_intro', models.TextField(default='intro')),
                ('api_brief_description', models.TextField(default='intro')),
                ('api_image', models.CharField(default='url_img', max_length=255)),
                ('api_subscribers', models.IntegerField(default=0)),
                ('api_category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='roniib_api.apicategories')),
            ],
        ),
        migrations.CreateModel(
            name='ApiEndpoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_name', models.CharField(max_length=255)),
                ('endpoint_url', models.CharField(max_length=255)),
                ('endpoint_desc', models.TextField(default='api description')),
                ('api_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roniib_api.apidocumentation')),
            ],
        ),
    ]
