# Generated by Django 4.2.5 on 2023-09-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roniib_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apidocumentation',
            name='api_total_requests',
            field=models.IntegerField(default=0),
        ),
    ]
