# Generated by Django 4.2.5 on 2023-09-05 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roniib_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiendpoints',
            name='endpoint_desc',
            field=models.TextField(default='api desc'),
        ),
    ]
