# Generated by Django 4.2.5 on 2023-09-05 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roniib_api', '0002_alter_apiendpoints_endpoint_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='apidocumentation',
            name='short_name',
            field=models.CharField(default='f', max_length=255),
        ),
    ]
